# Generated by Django 4.0.1 on 2022-01-12 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameResults',
            new_name='GameResult',
        ),
    ]
